

module.exports = {
  community: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
   
    {
      type: 'link',
      label: 'Join our Community Slack',
      href: 'https://aka.ms/playwright-slack',
    },
  ],
};