name: Roll
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1,5"

jobs:
  roll-docs:
    name: Roll Playwright to ToT
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'microsoft/playwright'
          path: playwright
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Roll
        run: npm run roll
        env:
          SRC_DIR: ./playwright
      - name: Prepare branch
        id: prepare-branch
        run: |
          BRANCH_NAME="roll/$(date +"%d-%m-%y")"
          set +e
          git diff -s --exit-code
          HAS_CHANGES="$?"
          set -e
          GIT_COMMIT="$(cd playwright && git rev-parse HEAD && cd ..)"
          echo "::set-output name=HAS_CHANGES::$HAS_CHANGES"
          echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"
          echo "::set-output name=GIT_COMMIT::$GIT_COMMIT"
          if [[ $HAS_CHANGES == 0 ]]; then
            echo "No changes detected, skipping PR"
            exit 0
          fi
          git config --global user.name github-actions
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "feat(roll): roll to ToT Playwright ($(date +"%d-%m-%y"))"
          git push origin $BRANCH_NAME --force
      - name: Create Pull Request
        uses: actions/github-script@v4
        if: ${{ steps.prepare-branch.outputs.HAS_CHANGES == '1' }}
        with:
          script: |
            await github.pulls.create({
              owner: 'microsoft',
              repo: 'playwright.dev',
              head: 'microsoft:${{ steps.prepare-branch.outputs.BRANCH_NAME }}',
              base: 'master',
              title: 'feat(roll): roll to ToT Playwright (${{ steps.prepare-branch.outputs.BRANCH_NAME }})',
              body: 'Upstream commit: https://github.com/microsoft/playwright/commit/${{ steps.prepare-branch.outputs.GIT_COMMIT }}',
            });
