name: Merge Roll Request

on:
  pull_request:
    branches:
      - 'roll/*'
    types:
      - opened
      - synchronize
  status:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for all checks to pass
        id: wait-for-checks
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            });
            console.log(JSON.stringify(result, null, 2));
            const allChecksPass = checks.check_runs.every((check) => check.conclusion === 'success');
            return allChecksPass;

    #   - name: Merge pull request
    #     if: steps.wait-for-checks.outputs.result == 'true'
    #     uses: actions/github-script@v4.2.0
    #     with:
    #       script: |
    #         await github.pulls.merge({
    #           owner: context.repo.owner,
    #           repo: context.repo.repo,
    #           pull_number: context.payload.pull_request.number,
    #           merge_method: 'squash',
    #         });
